### PR TITLE
fix: disable attribute inheritance by default, add option

### LINKED ISSUE #9: v2 copies heading classes/attributes to toc links - can we opt out?
hey, i've noticed that after upgrading to v2 my toc links suddenly inherited all the classes from the headings. like, if i have `<h2 class="text-2xl font-bold" id="foo">` the generated link becomes `<a href="#foo" class="text-2xl font-bold">` which breaks my toc styling pretty badly. in v1 this wasn't happening (or at least i didn't notice it), and i couldn't find an option to turn it off in the docs. would it be possible to add a setting to disable this? something like:

```js
eleventyConfig.addPlugin(pluginTOC, {
  copyAttributes: false,
});
```

```njk
{{ content | toc(copyAttributes=false) | safe }}
```

happy to contribute a PR if needed!

### PR DESCRIPTION
**Pull request by kotoyama**
closes #9

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -59,6 +61,12 @@ class Item {
 			if (el.hasAttributes()) {
```
Comment (uncenter) [inline src/index.js]:
```suggestion
			if (this.options.inheritAttributes && el.hasAttributes()) {
```

Technically this also includes empty arrays (which would mean inheriting none of them) but it isn't worth complicating this too much I think.

File: src/index.js [hunk 2]
```diff
@@ -59,6 +61,12 @@ class Item {
...
 				for (let attribute of el.attributes) {
 					if (['id'].includes(attribute.name)) continue; // skip id attribute
+					if (this.options.inheritAttributes === false) continue;
```
Comment (uncenter) [inline src/index.js]:
```suggestion
```
Replaced by the check above.

**Review by uncenter — COMMENTED** [review]
Just two minor comments - this looks great! Can we also add something about this to the README and update the default settings under #Configuring?

**Comment by uncenter** [comment]
Versioning this commit is interesting- technically a feature since it adds an option, but it also is a fix (`fix:`) reverts the behavior which is breaking (`fix!:`?) but fixes an early breaking change shipped in v2.1.0 so not actually breaking and maybe just a patch?

**Comment by kotoyama** [comment]
> Just two minor comments - this looks great! Can we also add something about this to the README and update the default settings under #Configuring?

sure, thanks for the review! committed both suggestions. the default config was already updated in the first commit, and i just added the extra note about `inheritAttributes`

**Comment by kotoyama** [comment]
> Versioning this commit is interesting- technically a feature since it adds an option, but it also is a fix (`fix:`) reverts the behavior which is breaking (`fix!:`?) but fixes an early breaking change shipped in v2.1.0 so not actually breaking and maybe just a patch?

yeah, fix or patch makes sense to me. we're basically restoring the pre-v2.1.0 behavior
